image: amazon/aws-cli:2.36.10

pipelines:
  branches:
    feature/payload-cms:
      - step:
          name: Test Bitbucket OIDC with AWS
          oidc: true
          script:
            - echo "===== AWS CLI ====="
            - aws --version

            - echo "===== OIDC TOKEN ====="
            - test -n "$BITBUCKET_STEP_OIDC_TOKEN"
            - echo "OIDC token received"

            - echo "===== CONFIGURE WEB IDENTITY ====="
            - export AWS_ROLE_ARN="arn:aws:iam::638501454103:role/BitbucketEcsCicdLabs"
            - export AWS_WEB_IDENTITY_TOKEN_FILE="$(pwd)/web-identity-token"

            - printf '%s' "$BITBUCKET_STEP_OIDC_TOKEN" > "$AWS_WEB_IDENTITY_TOKEN_FILE"

            - echo "===== AWS IDENTITY ====="
            - aws sts get-caller-identity

            - echo "===== OIDC SUCCESS ====="
