image: atlassian/default-image:4

pipelines:
  branches:
    feature/payload-cms:

      - step:
          name: Check Bitbucket Runner
          script:
            - echo "===== AWS CLI ====="
            - aws --version
            - echo "===== JQ ====="
            - jq --version
