services:

  postgres:
    image: postgres:17

    container_name: payload-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  payload:

    build: .

    container_name: payload-cms

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    env_file:
      - .env

    volumes:
      - .:/home/node/app

volumes:
  postgres_data:
